
name: CI

on: [push, pull_request]

jobs:
    ci:
        name: Build + Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            
            - name: Build Project
              run: ./gradlew :sample:assembleDebug
